services:
  frontend:
    image: itribe-v2-fe
    container_name: itribe-v2-fe
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=http://127.0.0.1:8000
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-networks
  backend:
    image: itribe-v2-be
    container_name: itribe-v2-be
    pull_policy: never
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
      - /app/obj
      - /app/bin
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
