services:
  frontend:
    image: nhanluong2812/itribe-v2-fe:latest
    container_name: itribe-v2-fe
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=/api
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-networks
    expose:
      - "3000"
  backend:
    image: nhanluong2812/itribe-v2-be:latest
    container_name: itribe-v2-be
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - data-protection-prod:/root/.aspnet/DataProtection-Keys
    networks:
      - app-networks
    expose:
      - "8000"
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: itribe-v2-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-networks
    depends_on:
      - frontend
      - backend
networks:
  app-networks:
    driver: bridge
volumes:
  data-protection-prod:
