name: Build and Deploy to VPS
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/itribe-v2-be:latest
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .z
          file: ./frontend/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/itribe-v2-fe:latest
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          key: ${{secrets.DO_SSH_KEY}}
          script: |
            cd /home/deploy/dotnet-ecommerce
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -af
